### ISSUE TITLE
More Sensors

### ISSUE THREAD

**Issue by entelzonta** [Vinz68/NeoPixel-Stair#3]
Hi,

I made one for my stairs, works well. I want to do it in my hallway, Can more sensors be added ? For example; 1 sensor is like controlling 1 meter.

Have a nice day

**Comment by Vinz68** [comment]
Hi Entelzonta,
Nice to know you used the script for your stairs. 
Don;t forget to give a star to show your appreciation ;)

I understand that you want to add a LedStrip for your hallway. That is a very cool idea.
So you probably want one extra PIR sensor to trigger the light in your hallway. This should not be a problem ; just use another input for this.

I think it would be possible to drive another (smaller strip) via another output for you hallway ; not 100% sure if library support this though. Maybe you can google on the used library 'Adafruit_NeoPixel'. Otherwise another arduino library should be used.
This library looks very promising and that is probably the one I would pick right now: https://github.com/FastLED/FastLED

Let me know if you can continue with this information and do not hesitate to add another comment if you need some help.

Would love to see a picture of your stair creation by the way :)

Best regards, Vincent.
